### ISSUE TITLE
Выгрузка товаров. Закрытие дня.

### ISSUE THREAD

**Issue by AndreyN-SanCity** [1CGoods/ModuleFor1C#27]
При закрытии дня выгружаются товары только по которым были движения (Приход) за указанный период. Из-за этого возникает ситуация как в случае изначально описанном в тексте задачи. 
Так-же при выгрузке необходимо учитывать пометку на удаление в базе.

**Comment by DAKopylov** [comment]
Исходный текст задачи: Товар куплен 20 октября, у поставщика, в личном кабинете, есть товар но нет поставщика.
Товар есть на остатках, в личном кабинете нет.

https://yadi.sk/i/fGDpYmJM3QEDbD

**Comment by asandulsky** [comment]
новый запрос в ежедневной выгрузке по Остаткам товаров
Текущие цены
Текущего поставщика

в Продажах
   из выгрузки продаж убрать очистку данных
   ЕГАИС

**Comment by AndreyN-SanCity** [comment]
ЕГАИС перенесли на 21 релиз

**Comment by AndreyN-SanCity** [comment]
ЕГАИС перенесли на 21 релиз

**Comment by AndreyN-SanCity** [comment]
![image](https://user-images.githubusercontent.com/34026602/33756978-1e5a829a-dc09-11e7-8159-18fe5b18fa6a.png)
