### ISSUE TITLE
УТ 10. Некорректное название магазина.

### ISSUE THREAD

**Issue by AndreyN-SanCity** [1CGoods/ModuleFor1C#31]
https://yadi.sk/i/JmQ6ukhq3QHdSS
Некорректное название магазина у нас в сервисе.

**Comment by DAKopylov** [comment]
На сервер передается наименование Магазина. Вероятно раньше было название "Розничный", а потом они поменяли. Так что тут либо тэг ошибка лишний, либо вопрос не в обработку.

P.S. Вот Json который пришел на сервер
{
"INN": "231500949121",
"KPP": "",
"DistrCode": "231500949121;",
"FirmName": "ИП Вычегжанина Наталья Валерьевна",
"FirmDirector": "",
"FirmAddress": "",
"StoreName": "Гастроном",
"НазваниеКонфигурации": "Управление торговлей, редакция 10.3",
"ВерсияКонфигурации": "10.3.43.1",
"PartnerCode": "",
"StoreAddress": "Сочи;Виноградная;4",
"Version": "19",
"Login": "andreyn@san-city.info",
"StoreCode": "231500949121;;Сочи;Виноградная;4"
}

**Comment by AndreyN-SanCity** [comment]
Проверил создание новой базы, все корректно.
