### ISSUE TITLE
Поиск поставщика по категориям товаров в 1С 

### ISSUE THREAD

**Issue by asandulsky** [1CGoods/ModuleFor1C#4]

**Comment by AndreyN-SanCity** [comment]
После добавления, непонятно что делать. Может добавить форму с отображением уже сформированных заявок?
![image](https://user-images.githubusercontent.com/34026602/34349313-58e7d8e2-ea21-11e7-9207-f4cd6621f06b.png)

**Comment by AndreyN-SanCity** [comment]
При отправке заявки по группе Алкогольные напитки, в самой заявке много групп товаров, в том числе и не алкогольных.
![image](https://user-images.githubusercontent.com/34026602/34349401-e9a3b5d6-ea21-11e7-81d7-a2cba9e3c5d1.png)
