### ISSUE TITLE
20 релиз в ОФ

### ISSUE THREAD

**Issue by AndreyN-SanCity** [1CGoods/ModuleFor1C#40]

**Comment by AndreyN-SanCity** [comment]
![image](https://user-images.githubusercontent.com/34026602/33818489-4a84c58e-de56-11e7-91bb-434abb1fded7.png)
Ошибка при расчете ассортиментной матрицы.

**Comment by DAKopylov** [comment]
https://yadi.sk/d/aTAYCfA23QVtSj - поправлено
